Export GSEA results as supplementary tables

In [1]:
from utils import *

In [2]:
os.chdir('../')

In [12]:
dft = pd.DataFrame()

idx = 0

for cell in ['Mono','DC','CD4T','B']:

    for dz in ['HRL','DCIS','BC']:

        idx += 1

        tmp = pd.read_csv(
            f'data/Tables/{cell}_{dz}.csv', 
            index_col=0
                     )

        tmp['Cell lineage'] = [cell] * tmp.shape[0]
    
        dft = tmp if idx==1 else pd.concat((dft, tmp))

dft

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes,log_p,analysis_group,analysis_db,Cell lineage
7,prerank,ANTIVIRAL INNATE IMMUNE RESPONSE,0.690128,1.639059,0.005222,0.046136,0.085,48.979592,14.37%,OAS1;TNF;DUS2;IFIT2;IFIT3;NLRP6;ZDHHC1;MX1;TBK...,1.335961,HRL,immport,Mono
10,prerank,INTERFERON ALPHA/BETA SIGNALING,0.669034,1.630316,0.000000,0.028106,0.099,57.142857,9.61%,IFITM3;IFITM1;IFITM2;HLA-E;OAS1;PTPN6;OAS3;JAK...,1.551204,HRL,immport,Mono
11,prerank,FC RECEPTOR MEDIATED STIMULATORY SIGNALING PAT...,0.776118,1.629417,0.001361,0.022485,0.099,36.363636,5.94%,LYN;HCK;FCER1G;MYO1G;FGR;VAV1;PRKCE;FYN,1.648114,HRL,immport,Mono
13,prerank,RAP1 SIGNALLING,0.814437,1.585849,0.014706,0.040303,0.213,46.666667,12.16%,RAP1B;RAP1GAP2;RASGRP2;YWHAZ;PRKACB;PRKACA;RAF1,1.394666,HRL,immport,Mono
14,prerank,FCGAMMA RECEPTOR (FCGR) DEPENDENT PHAGOCYTOSIS,0.614211,1.580750,0.001202,0.039109,0.230,34.117647,8.22%,LYN;FCGR3A;CYFIP2;HCK;PLD4;ACTR3;FGR;WASF2;VAV...,1.407718,HRL,immport,Mono
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,prerank,INTERFERON GAMMA SIGNALING,-0.600154,-1.738124,0.000000,0.006902,0.052,36.956522,11.65%,HLA-DPA1;HLA-B;B2M;PTPN6;HLA-DRA;HLA-C;IFI30;H...,2.161055,BC,immport,B
6,prerank,ROS AND RNS PRODUCTION IN PHAGOCYTES,-0.702670,-1.758047,0.001567,0.005320,0.034,48.571429,15.01%,RAC2;ATP6V0E1;ATP6V1G1;NCF1;CYBA;HVCN1;ATP6V1F...,2.274094,BC,immport,B
4,prerank,INTERLEUKIN-1 FAMILY SIGNALING,-0.575349,-1.776524,0.000000,0.004313,0.023,44.520548,11.77%,RPS27A;PTPN6;PSMB9;PSMA7;PSME1;ALOX5;UBB;UBA52...,2.365175,BC,immport,B
1,prerank,ANTIGEN PROCESSING AND PRESENTATION,-0.639577,-1.863355,0.000000,0.000863,0.002,29.347826,6.51%,HLA-DPA1;HLA-B;CD74;B2M;CD1C;HLA-DRA;CTSH;HLA-...,3.064145,BC,immport,B
0,prerank,TNFR2 NON-CANONICAL NF-KB PATHWAY,-0.704958,-2.066235,0.000000,0.000000,0.000,50.000000,10.34%,RPS27A;LTB;TNFRSF13B;PSMB9;CD40;CD27;TNFSF9;PS...,300.000000,BC,immport,B

In [13]:
dft = dft[['Cell lineage','analysis_group','Term','NES','NOM p-val', 'FDR q-val','Lead_genes']].reset_index(drop=True)
dft

,Cell lineage,analysis_group,Term,NES,NOM p-val,FDR q-val,Lead_genes
0,Mono,HRL,ANTIVIRAL INNATE IMMUNE RESPONSE,1.639059,0.005222,0.046136,OAS1;TNF;DUS2;IFIT2;IFIT3;NLRP6;ZDHHC1;MX1;TBK...
1,Mono,HRL,INTERFERON ALPHA/BETA SIGNALING,1.630316,0.000000,0.028106,IFITM3;IFITM1;IFITM2;HLA-E;OAS1;PTPN6;OAS3;JAK...
2,Mono,HRL,FC RECEPTOR MEDIATED STIMULATORY SIGNALING PAT...,1.629417,0.001361,0.022485,LYN;HCK;FCER1G;MYO1G;FGR;VAV1;PRKCE;FYN
3,Mono,HRL,RAP1 SIGNALLING,1.585849,0.014706,0.040303,RAP1B;RAP1GAP2;RASGRP2;YWHAZ;PRKACB;PRKACA;RAF1
4,Mono,HRL,FCGAMMA RECEPTOR (FCGR) DEPENDENT PHAGOCYTOSIS,1.580750,0.001202,0.039109,LYN;FCGR3A;CYFIP2;HCK;PLD4;ACTR3;FGR;WASF2;VAV...
...,...,...,...,...,...,...,...
250,B,BC,INTERFERON GAMMA SIGNALING,-1.738124,0.000000,0.006902,HLA-DPA1;HLA-B;B2M;PTPN6;HLA-DRA;HLA-C;IFI30;H...
251,B,BC,ROS AND RNS PRODUCTION IN PHAGOCYTES,-1.758047,0.001567,0.005320,RAC2;ATP6V0E1;ATP6V1G1;NCF1;CYBA;HVCN1;ATP6V1F...
252,B,BC,INTERLEUKIN-1 FAMILY SIGNALING,-1.776524,0.000000,0.004313,RPS27A;PTPN6;PSMB9;PSMA7;PSME1;ALOX5;UBB;UBA52...
253,B,BC,ANTIGEN PROCESSING AND PRESENTATION,-1.863355,0.000000,0.000863,HLA-DPA1;HLA-B;CD74;B2M;CD1C;HLA-DRA;CTSH;HLA-...
254,B,BC,TNFR2 NON-CANONICAL NF-KB PATHWAY,-2.066235,0.000000,0.000000,RPS27A;LTB;TNFRSF13B;PSMB9;CD40;CD27;TNFSF9;PS...

In [14]:
dft['Cell lineage'] = [
    'Monocyte' if x=='Mono' else
    'B cell' if x=='B' else
    'CD4 T cell' if x=='CD4T' else
    x for x in dft['Cell lineage']
]

In [15]:
dft.columns = ['Cell lineage','Group','Term','NES','NOM p-val','FDR q-val','Lead_genes']

In [16]:
dft.to_csv('data/Tables/ST_CNAgsea.csv')